name: Trials

on: 
  push:
    branches:
      - progress

jobs:
  test-pwd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ascension
        run: |
          # Performing a hard reset to undo any changes
          git reset --hard

          
          repoStr=${{ github.repository }}
          repoName=${repoStr#*/}
          git clone --single-branch --branch utopia https://www.github.com/${{ github.actor }}/${repoName}.git utopia-temp

          if [ -d "ascension" ]; then
            echo "Folder exists. Failing the workflow."
            exit 1
          else
            echo "Ascension folder does not exist. Continuing the workflow."
            mkdir ascension
          fi

          # Copying all files/directories except .git, ascension and utopia to the ascension folder
          rsync -av --exclude='.git' --exclude='ascension' --exclude='utopia-temp' ./ ascension

          # Copying the .git folder of utopia to the ascension folder
          cp -r ./utopia-temp/.git ./ascension/
          
          # Changing directory to the ascension folder
          cd ascension
          
          echo "----- dir -----"
          ls -al

          echo "----- git -----"
          git status

          #git config user.name "${{ github.actor }}"
          #git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add .
          git commit -m "Update utopia contents with progress"
          git push origin utopia
  
          # Go back to progress
          git checkout progress
          # Merge and push from utopia
          git merge utopia -X theirs
          git add .
          git push origin staging
        