name: Trials

on: 
  push:
    branches:
      - progress

jobs:
  test-pwd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          repository: 'mittons/CppDogDisplay'
          ref: 'utopia'
          path: utopia


      - name: Ascension
        run: |
          # Performing a hard reset to undo any changes
          git reset --hard

          if [ -d "ascension" ]; then
            echo "Folder exists. Failing the workflow."
            exit 1
          else
            echo "Ascension folder does not exist. Continuing the workflow."
            mkdir ascension
          fi

          # Copying all files/directories except .git, ascension and utopia to the ascension folder
          rsync -av --exclude='.git' --exclude='ascension' --exclude='utopia' ./ ascension

          # Copying the .git folder of utopia to the ascension folder
          cp -r ./utopia/.git ./ascension/
          
          # Changing directory to the ascension folder
          cd ascension
          
          echo "----- dir -----"
          dir